const languageData = {
  en: {
    title: "Mascota Match",
    navHome: "Home",
    navServices: "Services",
    navPlans: "Plans",
    navFAQ: "FAQ",
    langToggle: "ES",
    homeTitle: "Comprehensive care for your pet",
    homeDesc: "Connect with veterinarians, walkers and certified caregivers near you. All from an app, with tailored plans.",
    homeButton: "Discover Our App",
    servicesTitle: "Our Services",
    serviceWalks: "Safe Walks",
    serviceWalksDesc: "We offer supervised walks so your pet can enjoy physical activity in a safe and controlled environment.",
    serviceVetCheck: "Veterinary Check-Ups",
    serviceVetCheckDesc: "We perform regular checkups to ensure your pet’s health, with personalized consultations and advice.",
    serviceGrooming: "Grooming",
    serviceGroomingDesc: "We care for your pet’s coat with baths, cuts and grooming. Hygiene and well-being come first.",
    serviceEmergencies: "Emergencies",
    serviceEmergenciesDesc: "Rapid emergency care, with professionals ready to care for your pet when they need it most.",
    serviceVideosTitle: "Watch Our Services in Action",
    aboutProduct: "About the Product",
    aboutTeam: "About the Team",
    plansTitle: "Plans",
    planVIP: "VIP Plan",
    planVIPDesc: "Access to all our exclusive services, such as unlimited walks, priority attention in emergencies and personalized vaccine reminders.",
    planComplete: "Complete Plan",
    planCompleteDesc: "2 weekly walks, 1 grooming session per month, 1 home veterinary visit, vaccine and deworming monitoring, 24/7 support in the app.",
    planMini: "Mini Plan",
    planMiniDesc: "1 weekly walk, vaccine reminders, access to certified suppliers, monthly virtual review with veterinarian.",
    planCompleteWalks: "2 weekly walks",
    planCompleteGrooming: "1 grooming session per month",
    planCompleteVet: "1 home veterinary visit",
    planCompleteVaccine: "Vaccine and deworming monitoring",
    planCompleteSupport: "24/7 support in the app",
    planMiniWalks: "1 weekly walk",
    planMiniVaccine: "Vaccine reminders",
    planMiniSuppliers: "Access to certified suppliers",
    planMiniReview: "Monthly virtual review with veterinarian",
    readMore: "Read more",
    faqTitle: "Frequently Asked Questions",
    faqWalkingTitle: "How does the walking service work?",
    faqWalkingDesc: "Our certified walkers will be available according to your area. Choose the schedule that suits you best and enjoy a safe walk for your pet.",
    faqCertifiedTitle: "Are suppliers certified?",
    faqCertifiedDesc: "Yes, all veterinarians, walkers, groomers, and caregivers are verified and have the necessary experience to provide excellent service.",
    faqCancelTitle: "How can I cancel my subscription?",
    faqCancelDesc: "You can cancel your subscription at any time from the app, and you will not be charged the following month.",
    faqSubscribeTitle: "How can I subscribe to a plan?",
    faqSubscribeDesc: "You just have to download the app, choose the plan that suits you best, and complete the registration with your data.",
    faqChangeTitle: "Can I change plan at any time?",
    faqChangeDesc: "Yes, you can change your plan whenever you want from the app, without additional charges.",
    faqEmergenciesTitle: "What happens if my pet needs emergency care?",
    faqEmergenciesDesc: "With the complete and VIP plans, you have 24/7 support through the app. Additionally, you can contact urgent veterinarians if necessary.",
    footerLogo: "MascotaMatch",
    footerDistrictTitle: "District",
    footerDistrict: "Surquillo\nSan Borja\nSan Isidro",
    footerFollowTitle: "Follow Us",
    footerHours: "Customer Service Hours: Monday to Saturday: 8am to 9pm, Sunday: 8am to 8pm",
    footerContactTitle: "Contact",
    footerContact: "Email: contacto@mascotamatch.pe, Phone: 01 234 5678, WhatsApp: +51 987 654 321",
    footerCopyright: "© ManoloCorp Inc. S.A.C. TM © 2025. All Rights Reserved."
  },
  es: {
    title: "Mascota Match",
    navHome: "Inicio",
    navServices: "Servicios",
    navPlans: "Planes",
    navFAQ: "Preguntas Frecuentes",
    langToggle: "EN",
    homeTitle: "Cuidado integral para tu mascota",
    homeDesc: "Conéctate con veterinarios, paseadores y cuidadores certificados cerca de ti. Todo desde una app, con planes personalizados.",
    homeButton: "Descubre nuestra App",
    servicesTitle: "Nuestros Servicios",
    serviceWalks: "Paseos Seguros",
    serviceWalksDesc: "Ofrecemos paseos supervisados para que tu mascota disfrute de actividad física en un entorno seguro y controlado.",
    serviceVetCheck: "Chequeos Veterinarios",
    serviceVetCheckDesc: "Realizamos chequeos regulares para asegurar la salud de tu mascota, con consultas personalizadas y asesoramiento.",
    serviceGrooming: "Estética",
    serviceGroomingDesc: "Cuidamos el pelaje de tu mascota con baños, cortes y estética. La higiene y el bienestar son lo primero.",
    serviceEmergencies: "Emergencias",
    serviceEmergenciesDesc: "Atención de emergencia rápida, con profesionales listos para cuidar a tu mascota cuando más lo necesite.",
    serviceVideosTitle: "Mira nuestros servicios en acción",
    aboutProduct: "Sobre el Producto",
    aboutTeam: "Sobre el Equipo",
    plansTitle: "Planes",
    planVIP: "Plan VIP",
    planVIPDesc: "Acceso a todos nuestros servicios exclusivos, como paseos ilimitados, atención prioritaria en emergencias y recordatorios personalizados de vacunas.",
    planComplete: "Plan Completo",
    planCompleteDesc: "2 paseos semanales, 1 sesión de estética al mes, 1 visita veterinaria a domicilio, monitoreo de vacunas y desparacitación, soporte 24/7 en la app.",
    planMini: "Plan Mini",
    planMiniDesc: "1 paseo semanal, recordatorios de vacunas, acceso a proveedores certificados, revisión mensual virtual con veterinario.",
    planCompleteWalks: "2 paseos semanales",
    planCompleteGrooming: "1 sesión de estética al mes",
    planCompleteVet: "1 visita veterinaria a domicilio",
    planCompleteVaccine: "Monitoreo de vacunas y desparacitación",
    planCompleteSupport: "Soporte 24/7 en la app",
    planMiniWalks: "1 paseo semanal",
    planMiniVaccine: "Recordatorios de vacunas",
    planMiniSuppliers: "Acceso a proveedores certificados",
    planMiniReview: "Revisión mensual virtual con veterinario",
    readMore: "Leer más",
    faqTitle: "Preguntas Frecuentes",
    faqWalkingTitle: "¿Cómo funciona el servicio de paseos?",
    faqWalkingDesc: "Nuestros paseadores certificados estarán disponibles según tu área. Elige el horario que más te convenga y disfruta de un paseo seguro para tu mascota.",
    faqCertifiedTitle: "¿Están certificados los proveedores?",
    faqCertifiedDesc: "Sí, todos los veterinarios, paseadores, esteticistas y cuidadores están verificados y tienen la experiencia necesaria para ofrecer un excelente servicio.",
    faqCancelTitle: "¿Cómo puedo cancelar mi suscripción?",
    faqCancelDesc: "Puedes cancelar tu suscripción en cualquier momento desde la app, y no se te cobrará el mes siguiente.",
    faqSubscribeTitle: "¿Cómo puedo suscribirme a un plan?",
    faqSubscribeDesc: "Solo tienes que descargar la app, elegir el plan que más te convenga y completar el registro con tus datos.",
    faqChangeTitle: "¿Puedo cambiar de plan en cualquier momento?",
    faqChangeDesc: "Sí, puedes cambiar de plan cuando lo desees desde la app, sin cargos adicionales.",
    faqEmergenciesTitle: "¿Qué pasa si mi mascota necesita atención de emergencia?",
    faqEmergenciesDesc: "Con el plan completo y VIP, tienes soporte 24/7 a través de la app. Además, puedes contactar con veterinarios urgentes si es necesario.",
    footerLogo: "MascotaMatch",
    footerDistrictTitle: "Distrito",
    footerDistrict: "Surquillo\nSan Borja\nSan Isidro",
    footerFollowTitle: "Síguenos",
    footerHours: "Horario de atención al cliente: Lunes a Sábado: 8am a 9pm, Domingo: 8am a 8pm",
    footerContactTitle: "Contacto",
    footerContact: "Correo electrónico: contacto@mascotamatch.pe, Teléfono: 01 234 5678, WhatsApp: +51 987 654 321",
    footerCopyright: "© ManoloCorp Inc. S.A.C. TM © 2025. Todos los derechos reservados."
  }
};

const languageToggleButton = document.getElementById("lang-toggle");

languageToggleButton.addEventListener("click", () => {
  const currentLanguage = document.documentElement.lang;
  const newLanguage = currentLanguage === "en" ? "es" : "en";

  // Change the language
  document.documentElement.lang = newLanguage;

  // Update the language toggle button text
  languageToggleButton.textContent = languageData[newLanguage].langToggle;

  // Update all i18n elements with new language text
  const elements = document.querySelectorAll("[data-i18n-key]");
  elements.forEach(element => {
    const key = element.getAttribute("data-i18n-key");
    element.textContent = languageData[newLanguage][key];
  });
});
